### ISSUE TITLE
Question regarding the Jenkinsfile and docker-compose

### ISSUE THREAD

**Issue by seandelaney** [shipping-docker/dockerized-app#4]
Following the Shipping Docker video series but I have a question related to the `Jenkinsfile` in the https://course.shippingdocker.com/lessons/module-9/automating-tests video.

You are running `sh "./develop up -d"` and verbally mention in the video that the `./develop` bash script will run the CI version of the docker compose file. e.g `docker-compose.ci.yml`.

But how? You don't pass in a `BUILD_NUMBER` as per all your previous videos to call the CI version instead of the dev version?

**Comment by fideloper** [comment]
Hi!

BUILD_NUMBER is passed in by Jenkins automatically when it runs any
shell/bash script, so it's sort of "hidden" - it's set by Jenkins itself.

Sorry for the confusion on that point, I'll see if I can clear that up!

**Comment by seandelaney** [comment]
Ah! I actually remember you mentioning this... Thanks for the reminder.
