### ISSUE TITLE
Lesson 11 - Rolling Deployments

### ISSUE THREAD

**Issue by seandelaney** [shipping-docker/dockerized-app#6]
@fideloper 

I've managed to dockerize my laravel app by following the video tutorials.

My site will redirect users from HTTP to HTTPS but I can't get the rolling deployments part working!

On my server, I have copied the code snippet from the tutorial but changed the port from 80 to 443 since I'm running HTTPS by default:

```
upstream app {
	server my_nginx_phpfpm_1525109406:443;
}

server {
	listen 443;
	listen [::]:443;
	
	root /var/www/html;

	index index.html;

	server_name _;

	location / {
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_intercept_errors on;
		proxy_buffering on;
		proxy_buffer_size 128k;
		proxy_buffers 256 16k;
		proxy_busy_buffers_size 256k;
		proxy_temp_file_write_size 256k;
		proxy_max_temp_file_size 0;
		proxy_read_timeout 300;

		proxy_pass http://app;
		proxy_redirect off;

		# Handle Web Socket connections
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
```

I also pass in port 443 when starting the Nginx proxy container as per tutorial:

```
docker run -d --name=my_nginx_proxy --network=my_network --restart=always -v /opt/conf.d:/etc/nginx/conf.d -p 443:443 nginx:alpine
```

Everything seems to start up fine and when I do `docker ps -a`, I get:

```
6bcb1cc304bb        XXX        "start-container"        About a minute ago   Up About a minute                                              my_nginx_phpfpm_1525109406
30350ae0a533        nginx:alpine                   "nginx -g 'daemon of…"   10 minutes ago       Up 10 minutes        0.0.0.0:443->443/tcp   my_nginx_proxy
```

I don't have any errors when I check the Docker logs either for either container.

When I hit my URL, I get the "site cant be reached" message in Chrome.

Any suggestions on how to get your rolling deployments script to work with port 80 and port 443?

**Comment by fideloper** [comment]
Sorry, I was traveling recently - Sounds like you figured this out?

**Comment by seandelaney** [comment]
Yeah, I was trying to get my NGINX / PHP container running as HTTPS when in fact all I had to do was leave this running on HTTP and setup the NGINX proxy container to use HTTPS and everything worked.

**Comment by fideloper** [comment]
Great!
